name: Workflow Template - build push docker
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-push:
    runs-on: 
      - self-hosted
      - ${{ inputs.environment }}
    timeout-minutes: 7
    permissions:
      contents: read
      id-token: write
    steps:

    - name: Ensure environment is a docker tag
      shell: bash
      run: |
        if [[ ! "${{ inputs.environment }}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
          echo "ERROR: Invalid environment value. Must match ^[a-zA-Z0-9._-]+$"
          exit 1
        fi

    - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4

    - name: set vars
      shell: bash
      id: vars
      run: |-
        ISLANDORA_TAG=$(yq -r '."islandora-tag"' libops.yml)
        echo "tag=$ISLANDORA_TAG" >> $GITHUB_OUTPUT

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' # v2
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
        create_credentials_file: true
        service_account: ${{ secrets.GSA }}
        token_format: 'access_token'

    - uses: 'docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772' # v3
      name: 'Docker login'
      with:
        registry: 'us-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        context: .
        push: true
        build-args: |
          ISLANDORA_TAG=${{ steps.vars.outputs.tag }}
        tags: |
          us-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/private/drupal:${{ inputs.environment }}
