name: Workflow Template - libops.yml change
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      action:
        required: true
        type: string
        default: "set"
concurrency:
  group: libops-yml-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-libops-yml:
    permissions:
      contents: read
      id-token: write
    runs-on: 
      - self-hosted
      - development
    steps:
    - name: Ensure inputs are valid and transform branch name to valid docker tag
      shell: bash
      run: |
        if [[ ! "${{ inputs.branch }}" =~ ^[a-zA-Z0-9._-\/]+$ ]]; then
          echo "ERROR: Invalid branch value. Must match ^[a-zA-Z0-9._-]+$"
          exit 1
        fi
        if [[ ! "${{ inputs.action }}" =~ ^(set|del)$ ]]; then
          echo "ERROR: Invalid action. Must be set or del"
          exit 1
        fi
        TAG=$(echo "${{ inputs.branch }}" | sed 's/[^a-zA-Z0-9._-]//g' | awk '{print substr($0, length($0)-120)}')
        echo "tag=$TAG" >> $GITHUB_OUTPUT
      id: extract_tag

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' # v2
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
        create_credentials_file: true
        service_account: ${{ secrets.GSA }}
        token_format: 'access_token'

    - name: Deploy YAML
      run: |-
        set -eou pipefail

        CRED_FILE=$(echo "${{ steps.auth.outputs.credentials_file_path }}" | xargs basename)
        docker run --rm \
          --pull=always \
          -v $(pwd):/code \
          --env TF_VAR_libops_yaml=/code/libops.yml \
          --env GOOGLE_APPLICATION_CREDENTIALS=/code/$CRED_FILE \
          --env GOOGLE_PROJECT_ID="${{ secrets.GCLOUD_PROJECT }}" \
          us-docker.pkg.dev/libops-images/shared/deploy:main "${{ inputs.action }}" "${{ steps.extract_tag.outputs.tag }}" 
