name: Workflow Template - libops.yml change
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      action:
        required: false
        type: string
        default: "set"
concurrency:
  group: libops-yml-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-libops-yml:
    permissions:
      contents: read
      id-token: write
    runs-on: 
      - self-hosted
      - development
    steps:
    - name: Ensure inputs as valid
      shell: bash
      run: |
        if [[ ! "${{ inputs.branch }}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
          echo "ERROR: Invalid branch value. Must match ^[a-zA-Z0-9._-]+$"
          exit 1
        fi
        if [[ ! "${{ inputs.action }}" =~ ^(set|del)$ ]]; then
          echo "ERROR: Invalid action. Must be set or del"
          exit 1
        fi

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' # v2
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
        create_credentials_file: true
        service_account: ${{ secrets.GSA }}
        token_format: 'access_token'

    - uses: 'docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772' # v3
      name: 'Docker login'
      with:
        registry: 'us-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Deploy YAML
      run: /libops/scripts/tf-apply-isle.sh "${{ secrets.GCLOUD_PROJECT }}" "${{ steps.auth.outputs.credentials_file_path }}" "${{ inputs.action }}" "${{ inputs.branch }}"
