name: Ping environment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  ping:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-24.04
    steps:
    - uses: 'actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955' # v4
    - id: auth
      name: 'Fetch remote URLs'
      uses: 'google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed' # v2
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
        service_account: ${{ secrets.GSA }}
        token_format: 'access_token'
    - name: Extract Cloud Run URLs
      shell: bash
      run: |-
        echo "target=$(gcloud run services describe remote-${{ inputs.environment }} --region ${{ secrets.GCLOUD_REGION }} --format 'value(status.url)' --project ${{ secrets.GCLOUD_PROJECT }})" >> $GITHUB_OUTPUT
      id: get_cloudrun_urls
    - id: auth_target
      name: 'Authenticate to Google Cloud (source)'
      uses: 'google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed' # v2
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
        create_credentials_file: false
        service_account: ${{ secrets.GSA }}
        token_format: 'id_token'
        id_token_audience: ${{ steps.get_cloudrun_urls.outputs.target }}
    - name: Ping environment
      shell: bash
      run: |-
        set -eou pipefail

        COUNTER=0
        while [ 1 ]; do
          STATUS=$(curl -H "Authorization: Bearer ${{ steps.auth_target.outputs.id_token }}" \
            -w '%{http_code}' \
            -o /dev/null \
            -s \
            ${{ steps.get_cloudrun_urls.outputs.target }}/wakeup)
          if [ ${STATUS} -gt 199 ] && [ ${STATUS} -lt 300 ]; then
            echo "We're live 🚀"
            exit 0
          fi
          echo "Ping returned ${STATUS}"
          ((COUNTER++))
          if [ $COUNTER -eq 50 ]; then
            echo "Failed to come online after 4m"
            exit 1
          fi
          sleep 5;
        done
